version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: open_card_generator_production_django
    platform: linux/x86_64
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "8000:8000"

  celery:
    <<: *django
    image: celery-worker
    depends_on:
      - django
      - redis
    command: celery -A config.celery_app worker -l info -E
    ports: []
    volumes: []

  redis:
    image: redis
